apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: fluent-bit
spec:
  destination:
    name: 'in-cluster'
    namespace: observability
  source:
    repoURL: 'https://fluent.github.io/helm-charts'
    targetRevision: 0.39.0
    helm:
      releaseName: fluent-bit
      valueFiles:
        - ./values.yaml
    chart: fluent-bit
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas