apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    type: cluster-infra
  namespace: argocd
  name: fluentbit
spec:
  destination:
    name: 'in-cluster'
    namespace: observability
  source:
    repoURL: 'https://fluent.github.io/helm-charts'
    targetRevision: 0.39.0
    helm:
      releaseName: fluentbit
      valueFiles:
        - values.yaml
      parameters:
        - name: alertmanager.enabled
          value: 'false'
        - name: server.persistentVolume.enabled
          value: 'false'
        - name: alertmanager.persistentVolume.enabled
          value: 'false'
        - name: server.global.scrape_interval
          value: 15s
        - name: nodeExporter.service.hostPort
          value: '11005'
        - name: nodeExporter.service.servicePort
          value: '11005'
    chart: fluentbit
  project: default
  syncPolicy:
    syncOptions:
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas