apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-observability-apps
spec:
  template:
    metadata:
      labels:
        type: argocd-base
      namespace: argocd
      name: 'apps-observability'
    spec:
      destination:
        name: 'in-cluster'
        namespace: argocd
      source:
        path: './application/observability'
        repoURL: 'https://github.com/OrangeRed0706/argocd-deploy'
        targetRevision: main
      project: default