apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-namespaces-apps
spec:
  generators:
  - list:
      elements:
      - env: inner-cluster
  template:
    metadata:
      labels:
        type: argocd-base
      namespace: argocd
      name: 'apps-namespaces'
    spec:
      destination:
        name: 'in-cluster'
        namespace: argocd
      source:
        path: './namespaces'
        repoURL: 'https://github.com/OrangeRed0706/argocd-deploy'
        targetRevision: main
      project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:     
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10      