project: default
source:
  repoURL: 'https://github.com/OrangeRed0706/argocd-deploy'
  path: ./argoproj/stable/manifests
  targetRevision: HEAD
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
