apiVersion: v1
data:
  custom_parsers.conf: ""
  fluent-bit.conf: |
    [SERVICE]
        Flush     5
        Daemon    off
        Log_Level debug

    [INPUT]
        Name  cpu
        Tag   my_cpu

    [OUTPUT]
        Name  stdout
        Match my*cpu     
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluentbit
    meta.helm.sh/release-namespace: operation
  labels:
    app.kubernetes.io/instance: fluentbit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentbit
    app.kubernetes.io/version: 2.1.6
    helm.sh/chart: fluent-bit-0.34.1
  name: fluentbit
  namespace: operation